name: Build

on:
  push:
    branches: ["staging", "main"]

jobs:
  create-deployment-artifacts:
    name: Create Deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node installation
        run: npm install
      - name: Build steps
        run: |
          npm run build:client
          npm run build:server
      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev
      - name: Artisan caching
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Create deployment archive
        env:
          GITHUB_SHA: ${{github.sha}}
        run: tar -czf ${GITHUB_SHA}.tar.gz --exclude=node_modules --exclude=*.git *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{github.sha}}.tar.gz

  prepare-release-on-server:
    runs-on: ubuntu-latest
    needs: [create-deployment-artifacts]
    environment: ${{ contains(github.ref_name, 'main') && 'production' || 'staging'}}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: SCP Command to Transfer Artifact to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          source: ${{github.sha}}.tar.gz
          target: ${{secrets.SSH_PATH}}/private_html/artifacts
          tar_tmp_path: ${{secrets.SSH_PATH}}/private_html/temp

      - name: SSH Extract artifact and create folders
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_SHA: ${{github.sha}}
          RELEASE_PATH: ${{secrets.SSH_PATH}}/private_html/releases/${{github.sha}}
          ARTIFACTS_PATH: ${{secrets.SSH_PATH}}/private_html/artifacts
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          envs: RELEASE_PATH, ARTIFACTS_PATH, GITHUB_SHA
          script: |
            mkdir -p $ARTIFACTS_PATH
            mkdir -p $RELEASE_PATH
            tar -xzf ${ARTIFACTS_PATH}/${GITHUB_SHA}.tar.gz -C $RELEASE_PATH

  activate-release:
    name: "Activate release"
    runs-on: ubuntu-latest
    needs: [create-deployment-artifacts, prepare-release-on-server]
    environment: ${{ contains(github.ref_name, 'main') && 'production' || 'staging'}}
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_SHA: ${{github.sha}}
          RELEASE_PATH: ${{secrets.SSH_PATH}}/private_html/releases/${{github.sha}}
          ACTIVE_RELEASE_PATH: ${{secrets.SSH_PATH}}/public_html/current
          LARAVEL_ENV: ${{secrets.LARAVEL_ENV}}
          BASE_PATH: ${{secrets.SSH_PATH}}/public_html
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          envs: GITHUB_SHA, RELEASE_PATH, ACTIVE_RELEASE_PATH, LARAVEL_ENV, BASE_PATH
          script: |
            printf "%s" "$LARAVEL_ENV" > ${BASE_PATH}/.env
            ln -sf ${BASE_PATH}/.env $RELEASE_PATH
            ln -snf $RELEASE_PATH $ACTIVE_RELEASE_PATH
  clean-up:
    name: "Clean up"
    runs-on: ubuntu-latest
    needs:
      [create-deployment-artifacts, prepare-release-on-server, activate-release]
    environment: ${{ contains(github.ref_name, 'main') && 'production' || 'staging'}}
    steps:
      - name: Clean up
        uses: appleboy/ssh-action@v1.0.3
        env:
          RELEASES_PATH: ${{secrets.SSH_PATH}}/private_html/releases
          ARTIFACTS_PATH: ${{secrets.SSH_PATH}}/private_html/artifacts
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          envs: RELEASES_PATH, ARTIFACTS_PATH
          script: |
            cd $RELEASES_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
