name: Laravel

on:
  push:
    branches: ["staging"]

jobs:
  create-deployment-artifacts:
    name: Create Deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node installation
        run: npm install
      - name: Build steps
        run: |
          npm run build:client
      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --prefer-dist
      - name: Artisan caching
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Create deployment archive
        env:
          GITHUB_SHA: ${{github.sha}}
        run: tar -czf ${GITHUB_SHA}.tar.gz --exclude=node_modules --exclude=*.git *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{github.sha}}.tar.gz

  prepare-release-on-server:
    runs-on: ubuntu-latest
    needs: [create-deployment-artifacts]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: SCP Command to Transfer Artifact to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          source: ${{github.sha}}.tar.gz
          target: ${{secrets.SSH_PATH}}/artifacts
          tar_tmp_path: ${{secrets.SSH_PATH}}/temp

      - name: SSH Extract artifact and create folders
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          script: |
            mkdir -p ${{secrets.SSH_PATH}}/artifacts
            mkdir -p ${{secrets.SSH_PATH}}/releases/${{github.sha}}
            tar -xzf ${{secrets.SSH_PATH}}/artifacts/${{github.sha}}.tar.gz -C ${{secrets.SSH_PATH}}/releases/${{github.sha}}/

  activate-release:
    name: "Activate release"
    runs-on: ubuntu-latest
    needs: [create-deployment-artifacts, prepare-release-on-server]
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@v1.0.3
        env:
          GITHUB_SHA: ${{github.sha}}
          RELEASE_PATH: ${{secrets.SSH_PATH}}/releases/${{github.sha}}
          ACTIVE_RELEASE_PATH: ~/public_html/current/
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          port: ${{secrets.SSH_PORT}}
          envs: GITHUB_SHA, RELEASE_PATH, ACTIVE_RELEASE_PATH
          script: |
            ln -s -n -f $RELEASE_PATH $ACTIVE_RELEASE_PATH
