name: Laravel

on:
  push:
    branches: ["staging"]

jobs:
  create-deployment-artifacts:
    name: Create Deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node installation
        run: npm install
      - name: Build steps
        run: |
          npm run build:client
      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev --prefer-dist
      - name: Artisan caching
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Create deployment archive
        env:
          GITHUB_SHA: ${{github.sha}}
        run: tar -czf ${GITHUB_SHA}.tar.gz --exclude=node_modules --exclude=*.git *

      - name: Store artifact for distribution
        uses: actions/upload-artifacts@v4
        with:
          name: app-build
          path: ${{github.sha}}.tar.gz
